// This script contains an array which provides the source quote list.

var sourceQuotes = [
    {quote: "I'm sorry. If you were right, I'd agree with you.", 
     source: "Robin Williams",
     profession: "comedian"},
    {quote: "Conversation would be vastly improved by the constant use of four simple words: I do not know.", 
     source: "Andre Maurois",
     profession: "writer"},
    {quote: "A day without sunshine is like, you know, night.", 
     source: "Steve Martin",
     profession: "comedian"},
    {quote: "I love deadlines. I like the whooshing sound they make as they fly by.", 
     source: "Douglas Adams", 
     profession: "writer"},
    {quote: "There are lots of people who mistake their imagination for their memory", 
     source: "Josh Billings", 
     profession: "comedian"},
    {quote: "A mind needs books just like a sword needs a whetstone.", 
     source: "Tyrion Lannister", 
     citation: "Game of Thrones", 
     year: 2011,
     profession: "half-man"},
    {quote: "You waste time trying to get people to love you, and you'll end up the most popular dead man in town.", 
     source: "Ser Bronn of the Blackwater", 
     citation: "Game of Thrones" , 
     year: 2012,
     profession: "Lord Commander of the City Watch"},
    {quote: "Yeah I called her up, she gave me a bunch of crap about me not listenin' to her enough, or somethin'. I don't know, I wasn't really payin' attention.", 
     source: "Harry", 
     citation: "Dumb and Dumber" , 
     year: 1994,
     profession: "unemployed"},
    {quote: "Nobody calls me Lebowski. You got the wrong guy. I'm the Dude, man.", 
     source: "The Dude", 
     citation: "The Big Lebowski" , 
     year: 1998,
     profession: "unemployed"},
    {quote: "Sixty percent of the time, it works every time.", 
     source: "Brian Fantana", 
     citation: "Anchorman" , 
     year: 2004,
     profession: "weatherman"},
    {quote: "Hodor.",
     source: "Hodor",
     citation: "Game of Thrones",
     year: "Hodor",
     profession: "Hodor"
    },
    {quote: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
     source: "Marcus Aurelius",
     year: "A long time ago",
     profession: "politician"
    },
    {quote: "Life is a dream for the wise, a game for the fool, a comedy for the rich, a tragedy for the poor.",
     source: "Sholom Aleichem"},
    {quote: "Does it disturb anyone else that 'The Los Angeles Angels' baseball team name translates directly to 'The The Angels Angels'?",
     source: "Neil DeGrasse Tyson",
     citation: "Reader's Digest Funny Quotes",
     profession: "scientist"
    },
    {quote: "If con is the opposite of pro, then isn't Congress the opposite of progress?",
     source: "Jon Stewart",
     citation: "Reader's Digest Funny Quotes",
     profession: "comedian"
    },
    {quote: "What are they planting to grow the seedless watermelon?",
     source: "Jerry Seinfeld",
     citation: "Reader's Digest Funny Quotes",
     profession: "comedian"
    },
    {quote: "Children should be taught to question everything. To question everything they read, everything they hear. Children should be taught to question authority.",
     source: "George Carlin",
     citation: "It's Bad for Ya",
     year: 2008,
     profession: "comedian"
    },
    {quote: "Learning without thought is labor lost; thought without learning is perilous.",
     source: "Confucius",
     year: "551-470 BCE",
     profession: "philosopher"
    },
    {quote: "Problems that remain persistently insoluble should always be suspected as questions asked in the wrong way.",
     source: "Alan W. Watts",
     citation: "The Book on the Taboo Against Knowing Who You Are",
     year: 1989,
     profession: "philosopher"
    },
    {quote: "A man who does not think for himself does not think at all.",
     source: "Oscar Wilde",
     citation: "The Soul of Man under Socialism",
     year: 1891,
     profession: "author"
    },
    {quote: "Critical thinking is thinking about your thinking while you're thinking in order to make your thinking better.",
     source: "Richard W. Paul",
     citation: "How to Prepare Students for a Rapidly Changing World",
     year: 2012,
     profession: "scholar"
    },
    {quote: "To repeat what others have said requires education; to challenge it requires brains.",
     source: "Mary Pettibone Poole",
     citation: "A Glass Eye at a Keyhole",
     year: 1938,
     profession: "author"
    }
];