var quotes = [
    {quote: "I'm sorry. If you were right, I'd agree with you.", 
     source: "Robin Williams", 
     citation: null , 
     year: null,
     profession: "comedian"},
    {quote: "Conversation would be vastly improved by the constant use of four simple words: I do not know.", 
     source: "Andre Maurois", 
     citation: null , 
     year: null,
     profession: "writer"},
    {quote: "A day without sunshine is like, you know, night.", 
     source: "Steve Martin", 
     citation: null , 
     year: null,
     profession: "comedian"},
    {quote: "I love deadlines. I like the whooshing sound they make as they fly by.", 
     source: "Douglas Adams", 
     citation: null , 
     year: null,
     profession: "writer"},
    {quote: "There are lots of people who mistake their imagination for their memory", 
     source: "Josh Billings", 
     citation: null, 
     year: null,
     profession: "comedian"},
    {quote: "A mind needs books just like a sword needs a whetstone.", 
     source: "Tyrion Lannister", 
     citation: "Game of Thrones", 
     year: 2011,
     profession: "half-man"},
    {quote: "You waste time trying to get people to love you, and you'll end up the most popular dead man in town.", 
     source: "Ser Bronn of the Blackwater", 
     citation: "Game of Thrones" , 
     year: 2012,
     profession: "Lord Commander of the City Watch"},
    {quote: "Yeah I called her up, she gave me a bunch of crap about me not listenin' to her enough, or somethin'. I don't know, I wasn't really payin' attention.", 
     source: "Harry", 
     citation: "Dumb and Dumber" , 
     year: 1994,
     profession: "unemployed"},
    {quote: "Nobody calls me Lebowski. You got the wrong guy. I'm the Dude, man.", 
     source: "Dude", 
     citation: "The Big Lebowski" , 
     year: 1998,
     profession: "unemployed"},
    {quote: "Sixty percent of the time, it works every time.", 
     source: "Brian Fantana", 
     citation: "Anchorman" , 
     year: 2004,
     profession: "weatherman"}
];